name: avocado_ripeness_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip>=22.0.0
  - pip:
    - numpy>=1.20.0
    - pandas>=1.3.0
    - scikit-learn>=1.0.0
    - matplotlib>=3.4.0
    - seaborn>=0.11.0
    - mlflow>=2.0.0
    - joblib>=1.1.0