# MLflow Configuration
# This file contains additional configuration for MLflow tracking

# Experiment Configuration
experiment_name: "Avocado_Ripeness_Classification"
default_artifact_root: "./mlruns"

# Model Configuration
model_name: "AvocadoRipenessClassifier"
model_stage: "Production"

# Tracking Configuration
tracking_uri: "file:///app/mlruns"  # Local filesystem for Docker
log_model_history: true

# Hyperparameter Search Space
hyperparameters:
  n_estimators:
    min: 50
    max: 300
    default: 100
  max_depth:
    min: 5
    max: 50
    default: 20
  min_samples_split:
    min: 2
    max: 20
    default: 5
  min_samples_leaf:
    min: 1
    max: 10
    default: 2

# Metrics to Track
metrics:
  - accuracy
  - precision
  - recall
  - f1_score
  - roc_auc

# Artifacts to Save
artifacts:
  - confusion_matrix.png
  - feature_importance.png
  - model_summary.txt
  - training_log.txt

# Docker Configuration
docker:
  image_name: "avocado-ripeness-model"
  port: 5000
  health_check_endpoint: "/health"
  prediction_endpoint: "/predict"
